[build]
  publish = "_site/"
  command = "npx @11ty/eleventy"

[[plugins]]
  package = "@netlify/plugin-lighthouse"
  
[[plugins]]
  package = "@netlify/plugin-sitemap"

[[headers]]
  for = "/*"
  [headers.values]
    Content-Security-Policy = "default-src 'self';"