[build]
  publish = "_site/"
  command = "npx @11ty/eleventy"

[[plugins]]
  package = "@netlify/plugin-lighthouse"
  
[[plugins]]
  package = "@netlify/plugin-sitemap"

[[headers]]
  for = "/*"
  [headers.values]
    Content-Security-Policy = "default-src *; style-src 'self' 'unsafe-inline'; script-src 'self' 'unsafe-inline' 'unsafe-eval' http://www.google.com"