name: Build and Deploy Site
on:
  push:
    branches:
      - main
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    name: 'Deploy to Netlify'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Download Resume
        run: |
          mkdir -p src/_data && curl -o src/_data/resume.json https://github.com/kylegrantlucas/resume/releases/latest/download/kyle_modern.pdf
      - uses: jsmrcaga/action-netlify-deploy@v1.6.0
        with:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
          NETLIFY_DEPLOY_TO_PROD: true